# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f426867a-3663-4724-b59f-d1a7cf7d2ca9";
    fsType = "f2fs";
    options = [ "rw" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9ad63647-059b-4d17-b847-afe12a3fb355";
      fsType = "f2fs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9AFC-E999";
      fsType = "vfat";
    };
  fileSystems."/ntfs" =
    { device = "/dev/sda4";
      fsType = "ntfs"; 
      options = [ "rw" "uid=1000"];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
